language: ruby
rvm:
  - 2.3
services:
  - docker
before_install:
  - docker pull antora/antora
  - pwd
  - ls -la
  - docker run --rm --privileged --user=travis:travis -v $(pwd):/site -w="/site" antora/antora --cache-dir=./_antora_cache playbook.yml
  - docker ps -a
  - pwd
  - ls -la
  - ls -la ./_site
  - ls -la ./_site/documentation
  - ls -la ./_antora_cache
