language: ruby
rvm:
  - 2.3
services:
  - docker
before_install:
  - docker pull antora/antora
  - pwd
  - ls -la
  - docker run --rm --privileged --user=$UID:$GID -v $(pwd):/site -w="/site" antora/antora playbook.yml
  - docker ps -a
  - pwd
  - ls -la
  - ls -la ./_site
  - ls -la ./_site/documentation
